import { Inter } from 'next/font/google'
import Header from "@/app/component/Header"
import {Mulish} from 'next/font/google'
import Footer from "@/app/component/Footer";
 
const mulish = Mulish( {
  subsets: ['latin'],
  weight:'400',
  display: 'swap',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.classname}>
      
      <body>
      <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
